### ISSUE TITLE
The wrapper writes debug info to stdout when downloading

### ISSUE THREAD

**Issue by eiden** [takari/maven-wrapper#61] opened 2017-07-28 13:55 UTC
Ran into an issue where the wrapper pollutes stdout.
```
APPLICATION_VERSION=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec); echo "$APPLICATION_VERSION"

0.0.3-SNAPSHOT
```
```
rm -r ~/.m2/wrapper/dists/
APPLICATION_VERSION=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec); echo "$APPLICATION_VERSION"

Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.2.5/apache-maven-3.2.5-bin.zip
...................................................................................................................................................................................................................................................................................................................................................................................................................
0.0.3-SNAPSHOT
```
Please consider not writing this info to stdout, or write it to stderr.

**Comment by Gengar003** [comment] 2017-09-08 22:03
This is a duplicate of the (closed) issue #52, and related to PR #55. It looks like the maintainers intend to make this extra output off-by-default.

**Comment by yborovikov** [comment] 2017-09-12 17:23
At the very least the wrapper should respect `mvn`s `--quiet` and `-q` options.

**Comment by mosabua** [comment] 2017-09-12 18:21
We will not support mvn  parameters themselves

**Comment by mosabua** [comment] 2017-09-12 18:21
Also the download log is only on initial install and that is not a problem in our experience.

**Closed as completed by mosabua** 2017-09-12 18:21 UTC

**Comment by yborovikov** [comment] 2017-09-12 18:30
@mosabua
- the download might happen, e.g. on _every_ jenkins build - if the node is recycled.
- the wrapper certainly doesn't have to respect maven options, and in this case it should stay quiet _by default_ (e.g. not [echo project basedir](https://github.com/takari/maven-wrapper/blob/master/mvnw#L204) to stdout).

**Comment by mosabua** [comment] 2017-09-12 18:36
I just removed that a few minutes ago by introducing the verbose mode. I can look at the download stuff as well. Let me check

**Comment by mosabua** [comment] 2017-09-12 19:10
A new release is now out  .. but if you want the download and such to also be included in the log disabling you would have to look into creating a PR  .. or file and issue and wait if someone else takes that up.

**Comment by yborovikov** [comment] 2017-09-12 19:27
@mosabua awesome, thanks a lot!

**Comment by mosabua** [comment] 2017-09-12 19:28
I also released the maven plugin. Both should be on central..

**Comment by mosabua** [comment] 2017-10-26 05:51
Even more quiet now in the new release I just cut..
