### ISSUE TITLE
mvnw.cmd errors when used 

### ISSUE THREAD

**Issue by HopefulLlama** [takari/maven-wrapper#106] opened 2019-02-19 15:22 UTC
Hello, I installed the Maven wrapper today as the README instructs through: 
` mvn -N io.takari:maven:wrapper`

The install completes successfully, with `.mvn` directory created with expected files, as well as `mvnw` and `mvnw.cmd` created.

However, following on, trying to use the `mvnw.cmd` (on Windows of course), fails with the following message: 
```
.\mvnw.cmd clean
The syntax of the command is incorrect.
```

I'm not sure what the root of the problem is, but it seems like this is not the expected behaviour.

**Comment by mosabua** [comment] 2019-02-19 17:23
Can you provide more info and maybe pull request that fixes the issue? Also what wrapper version? Windows? Java?

**Comment by HopefulLlama** [comment] 2019-02-19 18:44
Wrapper version: `0.5.0`
Windows version:
```
Edition: Windows 10 Enterprise
Version: 1703
OS Build: 15063.1508
```
Java version: 
```
java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

**Comment by tbouffard** [comment] 2019-02-19 22:33
I also reproduce this issue (Windows 10, Oracle JDK 1.8.0_192. wrapper 0.5.0)
As a workaround, I have commented line 134-136
```bat
@REM 	if exist %MVNW_REPOURL% (
@REM 	  SET DOWNLOAD_URL="%MVNW_REPOURL%/io/takari/maven-wrapper/0.5.0/maven-wrapper-0.5.0.jar"
@REM 	)
```
The 3 lines above have been introduced in a1760e3eeef2adb883043b3702af5cdaf1a9c031
`if exist %MVNW_REPOURL%` in windows bat is to check if a file exists. Based on my understanding of the bat script and what is done in the sh script, I suppose we would like to check if the variable is set.
It could be replaced by `if not "%MVNW_REPOURL%" == ""` but it doesn't cover all cases (for instance if the variable  only contains 2 double quotes)

**Comment by mosabua** [comment] 2019-02-20 00:02
Great.. I will try to fix this .. if anyone else wants to chime in an send a PR that would be great. My bat file knowledge is very limited/outdated.

**Comment by mosabua** [comment] 2019-02-20 00:08
Tried the above now.. that works for me. I will cut a new release shortly.

**Comment by mosabua** [comment] 2019-02-20 05:11
Fixed by https://github.com/takari/maven-wrapper/pull/107

**Closed as completed by mosabua** 2019-02-20 05:11 UTC

**Comment by HopefulLlama** [comment] 2019-02-20 14:12
Thanks very much! Great work and quick too. 👍
