### ISSUE TITLE
mvnw fails to download from nexus oss

### ISSUE THREAD

**Issue by benbrummer** [takari/maven-wrapper#142] opened 2019-08-12 11:54 UTC
We are hosting an nexus oss. Configuring the settings.xml for maven to get everything from there makes the wrapper installation fail. Initially i was thinking this is an issue on nexus oss side, but as you can see here https://issues.sonatype.org/browse/NEXUS-20863 it does not look like that. Mvnw tries to download the maven-wrapper-0.5.5.tar.gz without authentication, which is not allowed on our repository manager. How can we configure the settings.xml that mvnw uses the credentials from the settings.xml?

**Comment by Stephan202** [comment] 2019-08-12 14:44
This issue was introduced in version 0.7.0 it seems. Given a `settings.xml` with a `<mirrorOf>*</mirrorOf>` configuration which proxies all artifact downloads to a Nexus instance which requires authentication:
* This works: `mvn io.takari:maven:0.6.1:wrapper -Dmaven.repo.local=/tmp/empty-dir-061`
* This doesn't work: `mvn io.takari:maven:0.7.0:wrapper -Dmaven.repo.local=/tmp/empty-dir-070`

The issue also reproduces with version 0.7.6. The error is:
> Server returned HTTP response code: 401 for URL: https://private-nexus-host/some-repo-proxying-to-maven-central/io/takari/maven-wrapper/0.5.0/maven-wrapper-0.5.0.tar.gz

Note that if the failing case is repeated then another error occurs:
> Error installing the Maven Wrapper.: Cannot determine the type of archive /tmp/empty-dir-070/io/takari/maven-wrapper/0.5.5/maven-wrapper-0.5.5.tar.gz. Input is not in the .gz format

This happens because an empty `maven-wrapper-0.5.5.tar.gz` is written.

**Comment by Mario-Eis** [comment] 2019-11-20 13:47
Any known workaround here?

**Comment by mosabua** [comment] 2019-11-20 15:23
You can configure authentication and then it should work just fine.

**Comment by benze** [comment] 2019-12-09 21:04
@mosabua I'm not sure I understand.  I configured my nexus credentials with 
```
 export MVNW_USERNAME
 export MVNW_PASSWORD
```

but when I rerun the installation:
```
mvn -N -X io.takari:maven:wrapper
...
...
[ERROR] Failed to execute goal io.takari:maven:0.7.7:wrapper (default-cli) on project standalone-pom: Error installing the Maven Wrapper.: Cannot determine the type of archive C:\Users\erbe\.m2\repository\io\takari\maven-wrapper\0.5.6\maven-wrapper-0.5.6.tar.gz. Input is not in the .gz format -> [Help 1]
...
...
Caused by: java.io.IOException: Input is not in the .gz format
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.init(GzipCompressorInputStream.java:164)
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:137)
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:102)
        at io.tesla.proviso.archive.tar.TarGzArchiveHandler.getInputStream(TarGzArchiveHandler.java:34)
        at io.tesla.proviso.archive.tar.TarGzArchiveSource.<init>(TarGzArchiveSource.java:27)
        ... 26 more

```

Indeed, I do not have a .tar.gz artifact in my own .m2 or in my local Nexus.  Anything else to try?

**Comment by mosabua** [comment] 2019-12-09 21:48
Something seems off with your server or local maven repo. Can you confirm that you can access the file in the repo. 

Here is the URL on central https://repo1.maven.org/maven2/io/takari/maven-wrapper/0.5.6/

you should be able to get the tar.gz easily on your Nexus .. provided it is configured to proxy central.

Both might have invalid files though .. Nexus and your local repo.. so get that fixed first.

**Comment by benbrummer** [comment] 2019-12-10 10:10
The issue is still present in 0.5.6.

Steps to reproduce:

**1. Nexus Repository Manager as proxy. Anonymous is disabled
2. Create a settings.xml like**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  
  <servers>
    <server>
      <id>nexus</id>
      <username>user</username>
      <password>password</password>
    </server>
  </servers>
  
  <mirrors>
    <mirror>
      <id>nexus</id>
      <mirrorOf>*</mirrorOf>
      <url>https://nexus.url/nexus/content/groups/public</url>
    </mirror>
  </mirrors>
  
  <profiles>
    <profile>
      <id>nexus</id>
      <repositories>
        <repository>
          <id>central</id>
          <url>https://central</url>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </snapshots>
        </repository>
      </repositories>
     <pluginRepositories>
        <pluginRepository>
          <id>central</id>
          <url>https://central</url>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
  
  <activeProfiles>
    <activeProfile>nexus</activeProfile>
  </activeProfiles>
</settings>
```
**3. Wipe your local maven repository
4. Clone https://github.com/vogellacompany/tycho-example
5. Try to update the wrapper**
```mvn -N io.takari:maven:0.7.7:wrapper```
**6. First run output:**
Looks good at first
```
...
Downloading from nexus: https://nexus.url/nexus/content/groups/public/org/eclipse/tycho/extras/tycho-pomless/1.5.1/tycho-pomless-1.5.1.pom
Downloaded from nexus: https://nexus.url/nexus/content/groups/public/org/eclipse/tycho/extras/tycho-pomless/1.5.1/tycho-pomless-1.5.1.pom (2.1 kB at 1.2 kB/s)
Downloading from nexus: https://nexus.url/nexus/content/groups/public/org/eclipse/tycho/extras/tycho-extras/1.5.1/tycho-extras-1.5.1.pom
Downloaded from nexus: https://nexus.url/nexus/content/groups/public/org/eclipse/tycho/extras/tycho-extras/1.5.1/tycho-extras-1.5.1.pom (16 kB at 112 kB/s)
Downloading from nexus: https://nexus.url/nexus/content/groups/public/io/takari/polyglot/polyglot-common/0.1.5/polyglot-common-0.1.5.pom
Downloaded from nexus: https://nexus.url/nexus/content/groups/public/io/takari/polyglot/polyglot-common/0.1.5/polyglot-common-0.1.5.pom (1.2 kB at 11 kB/s)
Downloading from nexus: https://nexus.url/nexus/content/groups/public/io/takari/polyglot/polyglot/0.1.5/polyglot-0.1.5.pom
Downloaded from nexus: https://nexus.url/nexus/content/groups/public/io/takari/polyglot/polyglot/0.1.5/polyglot-0.1.5.pom (6.5 kB at 56 kB/s)
Downloading from nexus: https://nexus.url/nexus/content/groups/public/io/takari/takari/14/takari-14.pom
...
```
but than fails for the wrapper
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.407 s
[INFO] Finished at: 2019-12-10T11:07:28+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.takari:maven:0.7.7:wrapper (default-cli) on project com.vogella.tycho.root: Error installing the Maven Wrapper.: Server returned HTTP response code: 401 for URL: https://nexus.url/nexus/content/groups/public/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.tar.gz -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
**6. Try again:**
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.433 s
[INFO] Finished at: 2019-12-10T11:09:16+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.takari:maven:0.7.7:wrapper (default-cli) on project com.vogella.tycho.root: Error installing the Maven Wrapper.: Cannot determine the type of archive C:\Users\BenjaminBrummer\.m2\repository\io\takari\maven-wrapper\0.5.6\maven-wrapper-0.5.6.tar.gz. Input is not in the .gz format -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
**7. Everything can be downloaded apart from the wrapper**
The request.log from nexus (support.zip) shows that the credentials from the settings.xml are used, BUT NOT for the wrapper. Therefore we get an http 401 error.

```
92.117.253.36 - user [10/Dec/2019:11:16:55 +0100] "GET /nexus/content/groups/public/io/takari/takari-archiver/0.1.9/takari-archiver-0.1.9.jar HTTP/1.1" 200 41189 5
92.117.253.36 - user [10/Dec/2019:11:16:55 +0100] "GET /nexus/content/groups/public/io/airlift/airline/0.6/airline-0.6.jar HTTP/1.1" 200 86653 62
92.117.253.36 - user [10/Dec/2019:11:16:55 +0100] "GET /nexus/content/groups/public/io/takari/takari-archiver/0.1.9/takari-archiver-0.1.9.jar.sha1 HTTP/1.1" 200 40 4
92.117.253.36 - user [10/Dec/2019:11:16:55 +0100] "GET /nexus/content/groups/public/io/airlift/airline/0.6/airline-0.6.jar.sha1 HTTP/1.1" 200 40 5
92.117.253.36 - user [10/Dec/2019:11:16:55 +0100] "GET /nexus/content/groups/public/io/takari/graph/takari-graph/0.0.3/takari-graph-0.0.3.jar.sha1 HTTP/1.1" 200 40 4
92.117.253.36 - - [10/Dec/2019:11:16:56 +0100] "GET /nexus/content/groups/public/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.tar.gz HTTP/1.1" 401 0 1
```
**8. The last working command/version:**
```mvn -N io.takari:maven:0.6.1:wrapper```
**9. The first failing command/version:**
```mvn -N io.takari:maven:0.7.0:wrapper```
**10. So the culprit is not in this repository but must be one of these**
https://github.com/takari/takari-maven-plugin/compare/maven-0.6.1...maven-0.7.0

**Comment by Aitozi** [comment] 2020-02-10 13:00
I have encountered the problem when i run `mvn -N io.takari:maven:wrapper`

```
[ERROR] Failed to execute goal io.takari:maven:0.7.7:wrapper (default-cli) on project test-case: Error installing the Maven Wrapper.: Cannot determine the type of archive /Users/aitozi/.m2/repository/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.tar.gz. Input is not in the .gz format -> [Help 1]
```

It was solved after deleting the file `maven-wrapper-0.5.6.tar.gz`

**Comment by benbrummer** [comment] 2020-02-10 13:21
@Aitozi are you using a private repository manager?

**Comment by Aitozi** [comment] 2020-02-10 13:38
@benbrummer Yes, I use the private settings.xml download once, then I think the problem was caused by the private repository, so I move the private settings.xml and encountered the problem above.

**Comment by mosabua** [comment] 2020-02-19 05:06
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.

**Closed as completed by mosabua** 2020-02-19 05:06 UTC
